################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# footer content
[en.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# footer content
[fr.params]
footer_content = "que la douleur soit grande, que l'elitr triste soit réglée, mais le diam nonumy qu'ils envient depuis longtemps, comme avec le travail et la douleur c'était grand pour certains, mais le plaisir du diam."
